apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
spec:
  ports:
  - port: 27017
    name: db
  clusterIP: None
  selector:
    app: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  serviceName: db
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
        replicaset: db
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: mongosecret   
            defaultMode: 256
      affinity: 
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - db
              topologyKey: kubernetes.io/hostname
      containers:
      - name: mongo
        image: mongo:4.1.8-xenial
        ports:
        - containerPort: 27017
          name: db
        command:
          - "mongod"
          - "--bind_ip"
          - "0.0.0.0"
          - "--replSet"
          - "db"
          - "--auth"
          - "--clusterAuthMode"
          - "keyFile"
          - "--keyFile"
          - "/etc/secret-volume/mongosecret"
          - "--setParameter"
          - "authenticationMechanisms=SCRAM-SHA-1"        
        volumeMounts:
        - name: secret-volume
          # readOnly: true
          mountPath: /etc/secret-volume/mongosecret
          subPath: mongosecret
        - name: dbdata
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: dbdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
